repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: check-poetry
  repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
- hooks:
  - id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
- hooks:
  - id: autoflake8
  repo: https://github.com/fsouza/autoflake8
  rev: v0.4.0
- hooks:
  - args:
    - --autofix
    id: pretty-format-toml
  - args:
    - --autofix
    id: pretty-format-yaml
  repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
- hooks:
  - args:
    - --profile
    - black
    id: isort
    name: isort (python)
  repo: https://github.com/pycqa/isort
  rev: 5.10.1
- hooks:
  - args:
    - --config-file
    - config/mypy.ini
    exclude: ^(docs/|example-plugin/|tests/fixtures)
    id: mypy
    additional_dependencies: [types-all]
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.982
- hooks:
  - entry: poetry run duty format
    id: format
    language: system
    name: run format task
    pass_filenames: false
    types:
    - python
  repo: local
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages: [push]
