---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 21.10b0  # Replace by any tag/version: https://github.com/psf/black/tags
      hooks:
          - id: black
            # Should be a command that runs python3.6+
            language_version: python3
    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: v1.0.0
      hooks:
          - id: check-poetry

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.3  # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict, -c, .yamllint.yaml]
            exclude: .github/workflows/ci.yml
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0  # or specific tag
      hooks:
          - id: yamlfmt
            exclude: tests/data/.*.yaml|mitmimage.yaml
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.29.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/fsouza/autoflake8
      rev: v0.2.2
      hooks:
          - id: autoflake8

    - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
      rev: v2.2.0
      hooks:
          - id: pretty-format-toml
            args: [--autofix]
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
          - id: isort
            name: isort (python)
            args: [--profile, black]
          - id: isort
            name: isort (cython)
            types: [cython]
          - id: isort
            name: isort (pyi)
            types: [pyi]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910-1
      hooks:
          - id: mypy
            exclude: ^(docs/|example-plugin/|tests/fixtures)
            args: [--config-file, config/mypy.ini]
    - repo: local
      hooks:
          - id: pytest
            name: Check pytest unit tests pass
            entry: poetry run duty test
            pass_filenames: false
            language: system
            types: [python]
