"""baseline

Revision ID: 4e4abd4fbc96
Revises:
Create Date: 2018-12-15 15:55:23.790542

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '4e4abd4fbc96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'sha256_checksum',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
        sa.Column('value', sa.String(), nullable=True),
        sa.Column('ext', sa.String(), nullable=True),
        sa.Column('filesize', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('img_format', sa.String(), nullable=True),
        sa.Column('img_mode', sa.String(), nullable=True),
        sa.Column('trash', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('value')
    )
    op.create_table(
        'url',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
        sa.Column(
            'value', sqlalchemy_utils.types.url.URLType(), nullable=False),
        sa.Column('sha256_checksum_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['sha256_checksum_id'], ['sha256_checksum.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url')
    op.drop_table('sha256_checksum')
    # ### end Alembic commands ###
