"""redirect and check

Revision ID: bbca83b18248
Revises: 4e4abd4fbc96
Create Date: 2018-12-15 16:01:32.070417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbca83b18248'
down_revision = '4e4abd4fbc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None, recreate='always') \
            as batch_op:
        batch_op.add_column(
            sa.Column('check_counter', sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                'last_check', sa.DateTime(),
                server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(
            sa.Column(
                'last_redirect', sa.DateTime(),
                server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
        batch_op.add_column(
            sa.Column('redirect_counter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_column('redirect_counter')
        batch_op.drop_column('last_redirect')
        batch_op.drop_column('last_check')
        batch_op.drop_column('check_counter')

    # ### end Alembic commands ###
